/* Automatically generated by configure - do not modify */
#define CONFIG_QE_PREFIX "/usr/local"
#define CONFIG_QE_DATADIR "/usr/local/share"
#define CONFIG_QE_MANDIR "/usr/local/man"
#define ARCH_X86 1
#define CONFIG_PTSNAME 1
#define QE_VERSION "5.2alpha"
#define CONFIG_WIN32 1
#define CONFIG_ALL_KMAPS 1
#define CONFIG_ALL_MODES 1
#define CONFIG_UNICODE_JOIN 1
#define CONFIG_MUTED_COLOR 1
